version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  type: zip
  files:
    - 'ROOT/WEB-INF/classes/application.properties'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/HelloWorldAppInitializer.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/ApplicationConfig.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/MvcConfig.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/controller/HelloWorldController.class'
    - 'ROOT/WEB-INF/lib/commons-fileupload-1.3.3.jar'
    - 'ROOT/WEB-INF/lib/commons-io-2.2.jar'
    - 'ROOT/WEB-INF/lib/spring-aop-5.0.7.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-beans-5.0.7.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-context-5.0.7.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-core-5.0.7.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-expression-5.0.7.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-jcl-5.0.7.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-web-5.0.7.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-webmvc-5.0.7.RELEASE.jar'
    - 'ROOT/WEB-INF/views/index.jsp'
    - 'ROOT/resources/gradients.css'
    - 'ROOT/resources/set-background.js'
    - 'ROOT/resources/styles.css'
    - 'ROOT/resources/tweet.svg'
